# -*- coding: utf-8 -*-
"""Final_Project_Kelompok9_Visdat05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1935KS2wW3FuQO9aYs-GgV655LvxJfj2l
"""

import pandas as pd
import numpy as np

# Bokeh libraries
from bokeh.io import output_file, output_notebook
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource,CDSView, GroupFilter
from bokeh.layouts import row, column, gridplot
from bokeh.models.widgets import Tabs, Panel
from bokeh.models import HoverTool

df = pd.read_csv('stock_market.csv',parse_dates=['Date'])
df.head()

adj_close = df.loc[:, ['Date', 'Adj Close', 'Name']]
adj_close.head()

output_file('Final Project Visualization Adj Close.html', 
            title='Visualisasi Data Interaktif Fluktuasi Harga Saham by Volume')
adj_close_cds = ColumnDataSource(adj_close)
HANG_SENG_view = CDSView(source = adj_close_cds,
                   filters = [GroupFilter(column_name='Name',group='HANG SENG')])
NASDAQ_view = CDSView(source = adj_close_cds,
                   filters = [GroupFilter(column_name='Name',group='NASDAQ')])
NIKKEI_view = CDSView(source = adj_close_cds,
                   filters = [GroupFilter(column_name='Name',group='NIKKEI')])

common_figure_kwargs_adj = {
    'plot_width': 800,
    'x_axis_label': 'Date',
}
common_circle_kwargs_adj = {
    'x': 'Date',
    'y': 'Adj Close',
    'source': adj_close_cds,
    'size': 12,
    'alpha': 0.7,
}
common_HANG_SENG_kwargs_adj = {
    'view': HANG_SENG_view,
    'color': '#CE1141',
    'legend': 'HANG SENG'
}
common_NASDAQ_kwargs_adj = {
    'view': NASDAQ_view,
    'color': '#006BB6',
    'legend': 'NASDAQ'
}
common_NIKKEI_kwargs_adj = {
    'view': NIKKEI_view,
    'color': '#007A33',
    'legend': 'NIKKEI'
}
hide_adj_fig = figure(**common_figure_kwargs_adj,
                  title='Click Legend to HIDE Data', 
                  y_axis_label='Adj Close')
hide_adj_fig.circle(**common_circle_kwargs_adj, **common_HANG_SENG_kwargs_adj)
hide_adj_fig.circle(**common_circle_kwargs_adj, **common_NASDAQ_kwargs_adj)
hide_adj_fig.circle(**common_circle_kwargs_adj, **common_NIKKEI_kwargs_adj)
hide_adj_fig.legend.click_policy = 'hide'
hide_adj_fig.add_tools(
            HoverTool(tooltips= [
            ('Date','@Date{%F}'),
            ('Adj Close', '$@{Adj Close}{%0.2f}'),
            ('Name','@Name'),
            ],
            formatters={
                '@Date'        : 'datetime', 
                '@{Adj Close}' : 'printf',   
                                        
            }))

volume = df.loc[:, ['Date', 'Volume', 'Name']]
volume.head()

volume_cds = ColumnDataSource(volume)
HANG_SENG_view = CDSView(source = volume_cds,
                   filters = [GroupFilter(column_name='Name',group='HANG SENG')])
NASDAQ_view = CDSView(source = volume_cds,
                   filters = [GroupFilter(column_name='Name',group='NASDAQ')])
NIKKEI_view = CDSView(source = volume_cds,
                   filters = [GroupFilter(column_name='Name',group='NIKKEI')])

common_figure_kwargs_vol = {
    'plot_width': 800,
    'x_axis_label': 'Date',
}
common_circle_kwargs_vol = {
    'x': 'Date',
    'y': 'Volume',
    'source': volume_cds,
    'size': 12,
    'alpha': 0.7,
}
common_HANG_SENG_kwargs_vol = {
    'view': HANG_SENG_view,
    'color': '#CE1141',
    'legend': 'HANG SENG'
}
common_NASDAQ_kwargs_vol = {
    'view': NASDAQ_view,
    'color': '#006BB6',
    'legend': 'NASDAQ'
}
common_NIKKEI_kwargs_vol = {
    'view': NIKKEI_view,
    'color': '#007A33',
    'legend': 'NIKKEI'
}
hide_vol_fig = figure(**common_figure_kwargs_vol,
                  title='Click Legend to HIDE Data', 
                  y_axis_label='Volume')
hide_vol_fig.circle(**common_circle_kwargs_vol, **common_HANG_SENG_kwargs_vol)
hide_vol_fig.circle(**common_circle_kwargs_vol, **common_NASDAQ_kwargs_vol)
hide_vol_fig.circle(**common_circle_kwargs_vol, **common_NIKKEI_kwargs_vol)
hide_vol_fig.legend.click_policy = 'hide'
hide_vol_fig.add_tools(
            HoverTool(tooltips= [
            ('Date','@Date{%F}'),
            ('Volume', '@Volume{0.00 a}'),
            ('Name','@Name'),
            ],
            formatters={
                '@Date'        : 'datetime',          
            }))

day_per_change = df.loc[:, ['Date', 'Day_Perc_Change', 'Name']]
day_per_change = day_per_change.sort_values(['Date','Name'])
day_per_change.head()

day_per_change_cds = ColumnDataSource(day_per_change)
HANG_SENG_view = CDSView(source = day_per_change_cds,
                   filters = [GroupFilter(column_name='Name',group='HANG SENG')])
NASDAQ_view = CDSView(source = day_per_change_cds,
                   filters = [GroupFilter(column_name='Name',group='NASDAQ')])
NIKKEI_view = CDSView(source = day_per_change_cds,
                   filters = [GroupFilter(column_name='Name',group='NIKKEI')])

common_figure_kwargs_dpc = {
    'plot_width': 800,
    'x_axis_label': 'Date',
}
common_circle_kwargs_dpc = {
    'x': 'Date',
    'y': 'Day_Perc_Change',
    'source': day_per_change_cds,
    'size': 12,
    'alpha': 0.7,
}
common_HANG_SENG_kwargs_dpc = {
    'view': HANG_SENG_view,
    'color': '#CE1141',
    'legend': 'HANG SENG'
}
common_NASDAQ_kwargs_dpc = {
    'view': NASDAQ_view,
    'color': '#006BB6',
    'legend': 'NASDAQ'
}
common_NIKKEI_kwargs_dpc = {
    'view': NIKKEI_view,
    'color': '#007A33',
    'legend': 'NIKKEI'
}
hide_dpc_fig = figure(**common_figure_kwargs_dpc,
                  title='Click Legend to HIDE Data', 
                  y_axis_label='Day_Perc_Change')
hide_dpc_fig.circle(**common_circle_kwargs_dpc, **common_HANG_SENG_kwargs_dpc)
hide_dpc_fig.circle(**common_circle_kwargs_dpc, **common_NASDAQ_kwargs_dpc)
hide_dpc_fig.circle(**common_circle_kwargs_dpc, **common_NIKKEI_kwargs_dpc)
hide_dpc_fig.legend.click_policy = 'hide'
hide_dpc_fig.add_tools(
            HoverTool(tooltips= [
            ('Date','@Date{%F}'),
            ('Day_Perc_Change', '@Day_Perc_Change'),
            ('Name','@Name'),
            ],
            formatters={
                '@Date'        : 'datetime',                                     
            }))

output_file('Final Project Visualization-tabbed_layout.html', 
            title='Visualisasi Data Interaktif Fluktuasi Harga Saham')
adj_close_panel = Panel(child=hide_adj_fig, title='Adj Close')
volume_panel = Panel(child=hide_vol_fig, title='Volume')
day_per_change_panel = Panel(child=hide_dpc_fig, title='Day_Perc_Change')
tabs = Tabs(tabs=[adj_close_panel, volume_panel,day_per_change_panel])
show(tabs)